amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.5   #里程计的旋转估计中来自旋转的预期过程噪声
    alpha2: 0.2   #里程计的旋转估计中来自平移的预期过程噪声
    alpha3: 0.2  #里程计的翻译估计中来自translation的预期过程噪声
    alpha4: 0.4  #里程计的平移估计中因旋转而产生的预期过程噪声
    alpha5: 0.2  #仅适用于 Omni 型号：translation噪音
    base_frame_id: "base_footprint" #机器人底座框架
    beam_skip_distance: 0.5         #忽略似然场模型中大多数粒子不同意的光束。考虑跳过的最大距离（米）
    beam_skip_error_threshold: 0.9  #由于收敛性不好，未匹配地图后强制进行完全更新的光束百分比
    beam_skip_threshold: 0.3        #需要跳过的光束的百分比。
    do_beamskip: false              #是否在似然场模型中进行波束跳跃
    global_frame_id: "map"          #定位系统发布的坐标框架的名称
    lambda_short: 0.1               #模型 z_short 部分的指数衰减参数
    laser_likelihood_max_dist: 2.0  #在地图上进行障碍物膨胀的最大距离，用于似然场模型
    laser_max_range: 12.0          #要考虑的最大扫描范围，-1.0 将导致使用激光报告的最大范围
    laser_min_range: 0.05           #要考虑的最小扫描范围，-1.0 将导致使用激光报告的最小范围
    laser_model_type: "likelihood_field" #使用哪种模型，
    #beam、likelihood_field 或 unlikely_field_prob。与 unlikely_field 相同，但如果启用，则包含 beamskip 功能
    max_beams: 60                   #更新过滤器时每次扫描要使用多少个均匀分布的光束。
    max_particles: 2000             #允许的最大粒子数
    min_particles: 500              #允许的最小粒子数
    odom_frame_id: "odom_combined"  #使用哪个框架进行里程计
    pf_err: 0.02                    #粒子过滤器群体误差
    pf_z: 0.85                      #粒子过滤器群体密度
    recovery_alpha_fast: 0.0        #快速平均权重过滤器的指数衰减率，用于决定何时通过添加随机姿势进行恢复。
    recovery_alpha_slow: 0.0        #慢速平均权重过滤器的指数衰减率，用于决定何时通过添加随机姿势进行恢复。
    resample_interval: 1            #重采样之前所需的过滤器更新次数
    robot_model_type: "nav2_amcl::DifferentialMotionModel" #插件类的完全限定类型。
    #选项为“nav2_amcl::DifferentialMotionModel”和“nav2_amcl::OmniMotionModel”。

    save_pose_rate: 0.5             #将最后估计的姿势和协方差存储到参数服务器的最大速率（Hz）
    sigma_hit: 0.02                 #模型的 z_hit 部分中使用的高斯模型的标准差
    tf_broadcast: true              #将其设置为 false 以防止 amcl 发布全局框架和里程计框架之间的变换
    transform_tolerance: 0.3        #发布转换的容差
    update_min_a: 0.06              #执行过滤器更新之前需要进行旋转运动。
    update_min_d: 0.025             #执行过滤器更新之前需要进行平移运动
    z_hit: 0.5                      #模型的 z_hit 部分的混合权重，所有使用的 z 权重之和必须为 1。
    z_max: 0.05                     #模型的 z_max 部分的混合权重，所有使用的 z 权重之和必须为 1。
    z_rand: 0.5                     #模型的 z_rand 部分的混合权重，所有使用的 z 权重之和必须为 1。
    z_short: 0.05                   #模型中 z_short 部分的混合权重，所有使用的 z 权重之和必须为 1。
    scan_topic: scan                #要订阅的激光雷达

    # Initial Pose
    set_initial_pose: True #AMCL 从 initial_pose* 参数设置初始姿势，而不是等待 initial_pose 消息
    initial_pose.x: 0.0
    initial_pose.y: 0.0
    initial_pose.z: 0.0
    initial_pose.yaw: 0.0
    #Amcl参数解释参考：https://docs.nav2.org/configuration/packages/configuring-amcl.html

amcl_map_client:
  ros__parameters:
    use_sim_time: False

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator:
  ros__parameters:
    use_sim_time: False
    transform_tolerance: 0.1 #变换容差
    goal_reached_tol: 0.25 #接受姿势作为目标的容忍度(m)
    global_frame: map
    robot_base_frame: base_footprint
    odom_topic: /odom_combined
    bt_loop_duration: 10        #BT 执行每次迭代的持续时间（以毫秒为单位
    default_server_timeout: 20  #BT 操作节点等待操作服务器确认时的默认超时值（以毫秒为单位）
    error_code_names:
    - compute_path_error_code
    - follow_path_error_code

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 30.0                      #运行控制器的频率 (hz)
    controller_plugins: ["FollowPath"]              # 用于处理请求和参数的控制器插件的映射名称列表
    odom_topic: /odom_combined                      #里程计话题名称

    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker" # "precise_goal_checker"

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.15
      yaw_goal_tolerance: 0.25
      stateful: True

    FollowPath:
      plugin: "nav2_rotation_shim_controller::RotationShimController" #旋转控制器
      primary_controller: "nav2_mppi_controller::MPPIController" #MPPI控制器
      time_steps: 56
      model_dt: 0.05
      batch_size: 2000
      vx_std: 0.2
      vy_std: 0.2
      wz_std: 0.4
      vx_max: 0.5
      vx_min: -0.5
      vy_max: 0.5
      wz_max: 2.0
      ax_max: 1.5
      ax_min: -1.5
      ay_max: 0.0
      az_max: 1.5
      iteration_count: 1
      prune_distance: 1.5
      enforce_path_inversion: false
      transform_tolerance: 0.1
      temperature: 0.3
      gamma: 0.015
      motion_model: "DiffDrive"
      visualize: false
      TrajectoryVisualizer:
        trajectory_step: 5
        time_step: 3
      AckermannConstraints:
        min_turning_r: 0.25
      critics: ["ConstraintCritic", "ObstaclesCritic", "GoalCritic", "GoalAngleCritic", "PathAlignCritic", "PathFollowCritic", "PathAngleCritic", "PreferForwardCritic"]
      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0

      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 0.5

      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 15.0
        threshold_to_consider: 1.4

      ObstaclesCritic:
        enabled: true
        cost_power: 1
        repulsion_weight: 1.5
        critical_weight: 30.0
        consider_footprint: false
        collision_cost: 10000.0
        collision_margin_distance: 0.1
        near_goal_distance: 0.4
        cost_scaling_factor: 5.0
        inflation_radius: 0.15

      PreferForwardCritic:
        enabled: true
        cost_power: 1
        cost_weight: 1.5
        threshold_to_consider: 0.5

      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 25.0
        max_path_occupancy_ratio: 0.07
        trajectory_point_step: 4
        threshold_to_consider: 0.5
        offset_from_furthest: 20
        use_path_orientations: false

      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0
        offset_from_furthest: 4
        threshold_to_consider: 0.5
        max_angle_to_furthest: 1.0
        mode: 0

      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 25.0
        offset_from_furthest: 5
        threshold_to_consider: 1.4

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom_combined
      robot_base_frame: base_footprint
      use_sim_time: False
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      # 车长0.42m、车宽0.32m，+1cm padding → 半长0.22、半宽0.17（假设 base_footprint 在几何中心）
      footprint: "[[-0.22, -0.17], [-0.22, 0.17], [0.22, 0.17], [0.22, -0.17]]"
      plugins: ["voxel_layer","inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.15
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 10.0
          # 限制 obstacle layer 的最小距離
          raytrace_min_range: 0.05
          obstacle_max_range: 2.5
          # 限制 obstacle layer 的最小距離
          obstacle_min_range: 0.05

      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_footprint
      use_sim_time: False
      # 车长0.42m、车宽0.32m，+1cm padding → 半长0.22、半宽0.17（假设 base_footprint 在几何中心）
      footprint: "[[-0.22, -0.17], [-0.22, 0.17], [0.22, 0.17], [0.22, -0.17]]"
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 10.0
          # 限制 obstacle layer 的最小距離
          raytrace_min_range: 0.05
          obstacle_max_range: 2.5
          # 限制 obstacle layer 的最小距離
          obstacle_min_range: 0.05
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 10.0
        inflation_radius: 0.20
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: False
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "avalue.yaml"

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      tolerance: 0.25
      downsample_costmap: false
      downsampling_factor: 1
      allow_unknown: false
      max_iterations: 1000000
      max_on_approach_iterations: 1000
      max_planning_time: 5.0
      motion_model_for_search: "DUBIN"
      cost_travel_multiplier: 2.0
      angle_quantization_bins: 72
      analytic_expansion_ratio: 3.5
      analytic_expansion_max_cost: 200.0
      minimum_turning_radius: 0.20
      reverse_penalty: 1.2
      change_penalty: 0.2
      non_straight_penalty: 1.5
      cost_penalty: 2.5
      lookup_table_size: 20.0
      cache_obstacle_heuristic: True
      smooth_path: true
      smoother:
        max_iterations: 1000
        w_smooth: 0.3
        w_data: 0.2
        tolerance: 1.0e-10

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

smoother_server:
  ros__parameters:
    use_sim_time: True
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 0.1
      max_its: 1000
      do_refinement: True

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200
